# Generated by Django 2.2 on 2022-02-10 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='created_on',
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
